/** 在线免费字体目录（按需下载，未入库前显示 ↓） */
export const ONLINE_FREE_FONTS = [
  {
    id: 'zcool-kuaile',
    name: '站酷快乐体',
    category: '装饰',
    sampleText: '站酷快乐体',
    downloadUrl: 'https://cdn.wpx.app/fonts/free/zcool-kuaile.ttf',
    fileName: 'zcool-kuaile.ttf',
  },
  {
    id: 'zcool-wenyi',
    name: '站酷文艺体',
    category: '手写',
    sampleText: '站酷文艺体',
    downloadUrl: 'https://cdn.wpx.app/fonts/free/zcool-wenyi.ttf',
    fileName: 'zcool-wenyi.ttf',
  },
  {
    id: 'muyao-soft',
    name: '沐瑶软笔手写体',
    category: '手写',
    sampleText: '沐瑶软笔手写体',
    downloadUrl: 'https://cdn.wpx.app/fonts/free/muyao-soft.ttf',
    fileName: 'muyao-soft.ttf',
  },
  {
    id: 'smile-black',
    name: '得意黑',
    category: '黑体',
    sampleText: '得意黑',
    downloadUrl: 'https://cdn.wpx.app/fonts/free/smile-black.ttf',
    fileName: 'smile-black.ttf',
  },
  {
    id: 'source-han-soft',
    name: '思源柔黑',
    category: '黑体',
    sampleText: '思源柔黑',
    downloadUrl: 'https://cdn.wpx.app/fonts/free/source-han-soft.ttf',
    fileName: 'source-han-soft.ttf',
  },
  {
    id: 'biaoxiaozhi-longzhu',
    name: '标小智龙珠体',
    category: '装饰',
    sampleText: '标小智龙珠体',
    downloadUrl: 'https://cdn.wpx.app/fonts/free/biaoxiaozhi-longzhu.ttf',
    fileName: 'biaoxiaozhi-longzhu.ttf',
  },
  {
    id: 'jiying-wensong',
    name: '极影毁片文宋',
    category: '宋体',
    sampleText: '极影毁片文宋',
    downloadUrl: 'https://cdn.wpx.app/fonts/free/jiying-wensong.ttf',
    fileName: 'jiying-wensong.ttf',
  },
  {
    id: 'misans',
    name: 'MiSans',
    category: '黑体',
    sampleText: 'MiSans',
    downloadUrl: 'https://cdn.wpx.app/fonts/free/misans.ttf',
    fileName: 'misans.ttf',
  },
]
