/** tui.image-editor 中文 locale */
export const editorLocale = {
  Crop: '裁剪',
  Rotate: '旋转',
  Flip: '翻转',
  'Flip X': '水平翻转',
  'Flip Y': '垂直翻转',
  Reset: '重置',
  Draw: '绘制',
  Shape: '标注',
  Icon: '图标',
  Text: '文字',
  Mask: '马赛克',
  Filter: '调色',
  Bold: '粗体',
  Italic: '斜体',
  Underline: '下划线',
  Left: '左对齐',
  Center: '居中',
  Right: '右对齐',
  Color: '颜色',
  'Text size': '字号',
  Range: '角度',
  Apply: '应用',
  Cancel: '取消',
  Custom: '自定义',
  Square: '正方形',
  Rectangle: '矩形',
  Circle: '圆形',
  Triangle: '三角形',
  Fill: '填充',
  Stroke: '描边',
  Grayscale: '灰度',
  Invert: '反色',
  Sepia: '复古',
  Sepia2: '复古2',
  Blur: '模糊',
  Sharpen: '锐化',
  Emboss: '浮雕',
  'Remove White': '去白',
  Distance: '距离',
  Brightness: '亮度',
  Noise: '噪点',
  Pixelate: '像素化',
  'Color Filter': '颜色滤镜',
  Threshold: '阈值',
  Tint: '色调',
  Multiply: '正片叠底',
  Blend: '混合',
  Width: '宽度',
  Height: '高度',
  'Lock Aspect Ratio': '锁定比例',
  'Load Mask Image': '加载遮罩图',
  Hand: '抓手',
  'Zoom In': '放大',
  'Zoom Out': '缩小',
  History: '历史',
  Undo: '撤销',
  Redo: '重做',
  Delete: '删除',
  'Delete-all': '全部删除',
}

/** 浅色主题，隐藏品牌 logo 区域；load/download 按钮由 CSS display:none 隐藏 */
export const editorTheme = {
  'common.backgroundColor': '#f8fafc',
  'common.border': '0px',
  'header.backgroundColor': 'transparent',
  'header.border': '0px',
  'menu.backgroundColor': 'transparent',
  'menu.normalIcon.color': '#64748b',
  'menu.activeIcon.color': '#7c3aed',
  'menu.disabledIcon.color': '#cbd5e1',
  'submenu.backgroundColor': 'rgba(255, 255, 255, 0.55)',
  'submenu.partition.color': '#e2e8f0',
  'submenu.normalLabel.color': '#475569',
  'submenu.activeLabel.color': '#7c3aed',
  'checkbox.border': '1px solid #cbd5e1',
  'checkbox.backgroundColor': '#fff',
  'range.pointer.color': '#7c3aed',
  'range.bar.color': '#e2e8f0',
  'range.subbar.color': '#7c3aed',
  'range.value.color': '#475569',
  'range.value.backgroundColor': '#f1f5f9',
  'range.title.color': '#475569',
}

export const EDITOR_MENUS = ['crop', 'rotate', 'shape', 'text']

/** 顶栏基线高度：标题行(36) + 图标工具栏(40) + 子菜单栏(48)
 *  实际运行期通过 getBoundingClientRect() 动态获取，错误条等动态内容变化时自动调整 */
export const IMAGE_EDITOR_HEADER_BASE_H = 124
export const IMAGE_EDITOR_FOOTER_H = 52
